### ISSUE TITLE
Usage of version numbers and semantic versioning

### ISSUE THREAD

**Issue by KarlSchu** [SolarEnergyRacers/solar_car_control_system#146]
We should introduce a versioning. For now there is a version in definitions.h: 
#define VERSION "v0.1"
#define VERSION_PUBLISHED "2022.01"

It is used in CarState and the serial console log.

**Comment by andreaskuster** [comment]
I suggest we use the commit hash instead. This could for example be done using the following command: `git rev-parse --short HEAD`

**Comment by andreaskuster** [comment]
And for releases, I would use releases function present on github
