### ISSUE TITLE
Fix CAN Problems!!!

### ISSUE THREAD

**Issue by tomajon1** [SolarEnergyRacers/solar_car_control_system#40]
Write Email to Prohelion

User Manual:
"COMMUNICATIONS
The CAN standard does not specify high-level message protocols. Prohelion devices use a
custom protocol, outlined in the communication specification document for each device.
By default, each device operates at 500 kbits/second and comes programmed from the factory
with a CAN base address that will allow it to work in unison with other Prohelion devices. The
CAN bit rate and base address can be set with the Windows BMS configuration software."

**Comment by tomajon1** [comment]
Hi Jonas,
 
This functionality is not yet in Profinity, you will need to use the old Tritium tools.
 
Make sure you get the latest versions of BMS Viewer and CAN-Ethernet bridge configuration:
 
 BMS_Viewer_2_00.exe
 CanBridgeConfigInstaller_2_04.msi
 
 
If you run the BMS viewer software:
 
1.	Setup->BMS Configuration
2.	Change CAN Bitrate to desired rate:
 
3.	 
![image](https://user-images.githubusercontent.com/63045737/114348954-8ded2d80-9b67-11eb-83bb-637d14ec940b.png)

 
4.	Then: Transfer->Save to BMU
 
The BMU is now running on the new rate but you will have now lost communications so will need to change the rate on the CAN Bridge:
 
Go to CAN-Ethernet Bridge Configuration:
5.	Change Bit Rate
 
![image](https://user-images.githubusercontent.com/63045737/114348980-96ddff00-9b67-11eb-92ab-d80cedf17080.png)

Hit:  Store
 
And you should now be communicating on the same bitrate.
 
Kind regards,
 
Anthony Prior
CEO
M: +61 411 098 131

**Comment by andreaskuster** [comment]
@Damian:

(1) read datasheet
(2) set bitrate to 125k
(3) get it working :)
- possible solution: twisted-pair cable
- oscillator debugging

**Comment by tomajon1** [comment]
CAN-Ethernet Bridge Configuration does not work on Windows 7

**Comment by andreaskuster** [comment]
Solved & PR created.
