### ISSUE TITLE
Electronic Component Placement (within the Car)

### ISSUE THREAD

**Issue by andreaskuster** [SolarEnergyRacers/solar_car_control_system#72]
#### SER-4 Montage Steuerung/Elektrik

Könnt Ihr mal skizzieren, wo Ihr welche elektrischen Komponenten montieren wollt,
und welches mechanische Montagematerial Ihr dafür benötigt (Alu-Flanche u.ä.)
 
Besten Dank !

**Comment by garned** [comment]
Erster Vorschlag:
MC links aussen an den Längsträger und der uC auf die gegenüberliegende Innenseite.

**Comment by KarlSchu** [comment]
![image](https://user-images.githubusercontent.com/65240764/122683635-d62c6a00-d200-11eb-96a5-7e83fa8a5bec.png)
