### ISSUE TITLE
Register ../interfaces as components

### ISSUE THREAD

**Issue by KarlSchu** [SolarEnergyRacers/solar_car_control_system#85]
Register ../interfaces/abstract_task.h as component to include the header as usual i.e. #include <abstract_task.h>

**Comment by andreaskuster** [comment]
@KarlSchu Is this an old issue (that can be closed) or still pending? To my understanding, this should already be in place, see the `CMakeLists.txt` and `*.mk` file: https://github.com/SolarEnergyRacers/solar_car_control_system/tree/master/interfaces
